/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Nov 25, 2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.TransparentPasswordField;
import hotellounge.vista.base.TransparentTextField;
import javax.swing.JFrame;

/**
 *
 * @author jmora
 */
public class About extends javax.swing.JDialog {

    /**
     * Creates new form IniciarSesion
     */
    public About(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panel_tituloabout = new hotellounge.vista.base.PanelConFondo();
        lbl_DD = new javax.swing.JLabel();
        panel_infoabout = new hotellounge.vista.base.PanelConFondo();
        lbl_Melvin = new javax.swing.JLabel();
        lbl_Gil = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        lbl_JoseMora1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_tituloabout.setFondo(bundle.getString("About.panel_tituloabout.fondo")); // NOI18N

        lbl_DD.setFont(Principal.getLetraTexto1());
        lbl_DD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_DD.setText(bundle.getString("About.lbl_DD.text")); // NOI18N
        panel_tituloabout.add(lbl_DD);
        lbl_DD.setBounds(20, 10, 330, 40);

        panelBase1.add(panel_tituloabout);
        panel_tituloabout.setBounds(50, 20, 370, 60);

        panel_infoabout.setFondo(bundle.getString("About.panel_infoabout.fondo")); // NOI18N

        lbl_Melvin.setFont(Principal.getLetraTexto3());
        lbl_Melvin.setText(bundle.getString("About.lbl_Melvin.text")); // NOI18N
        panel_infoabout.add(lbl_Melvin);
        lbl_Melvin.setBounds(30, 130, 310, 40);

        lbl_Gil.setFont(Principal.getLetraTexto3());
        lbl_Gil.setText(bundle.getString("About.lbl_Gil.text")); // NOI18N
        panel_infoabout.add(lbl_Gil);
        lbl_Gil.setBounds(30, 30, 310, 40);

        btn_cancelar.setText(bundle.getString("About.btn_cancelar.text")); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        panel_infoabout.add(btn_cancelar);
        btn_cancelar.setBounds(250, 180, 100, 40);

        lbl_JoseMora1.setFont(Principal.getLetraTexto3());
        lbl_JoseMora1.setText(bundle.getString("About.lbl_JoseMora1.text")); // NOI18N
        panel_infoabout.add(lbl_JoseMora1);
        lbl_JoseMora1.setBounds(30, 80, 310, 40);

        panelBase1.add(panel_infoabout);
        panel_infoabout.setBounds(50, 90, 370, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void mostrar_error(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "¡Error!", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel lbl_DD;
    private javax.swing.JLabel lbl_Gil;
    private javax.swing.JLabel lbl_JoseMora1;
    private javax.swing.JLabel lbl_Melvin;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_infoabout;
    private hotellounge.vista.base.PanelConFondo panel_tituloabout;
    // End of variables declaration//GEN-END:variables
}
