/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * 15-dic-2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.modelo.Habitacion;
import hotellounge.vista.base.VentanaBase_admin;

/**
 *
 * @author Oscar
 */
public class AdministrarHabitaciones extends VentanaBase_admin {

    /**
     * Creates new form AdministrarHabitaciones
     */
    public AdministrarHabitaciones() {
        initComponents();
        
        //Se popula el comboBox con las opciones
        Habitacion habitaciones[] = Principal.getHabitaciones();
        for (int i = 0; i < habitaciones.length; i++) {
            if (habitaciones[i] != null) {
                cmbb_tiposdeH.addItem(habitaciones[i].getTipo());
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panel_cantdeH = new hotellounge.vista.base.PanelConFondo();
        btn_additem = new hotellounge.vista.base.PanelConFondo();
        btn_minusitem = new hotellounge.vista.base.PanelConFondo();
        trans_CantidadH = new hotellounge.vista.base.TransparentTextField();
        text_canthabitaciones = new javax.swing.JLabel();
        panel_TiposdeH = new hotellounge.vista.base.PanelConFondo();
        text_tiposdeH = new javax.swing.JLabel();
        cmbb_tiposdeH = new javax.swing.JComboBox();
        panel_save = new hotellounge.vista.base.PanelConFondo();
        btn_save = new hotellounge.vista.base.PanelConFondo();
        text_save = new javax.swing.JLabel();
        btn_regresar = new hotellounge.vista.base.PanelConFondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_cantdeH.setFondo(bundle.getString("MisReservaciones.panel_info.fondo")); // NOI18N

        btn_additem.setFondo(bundle.getString("MisReservaciones.panelConFondo4.fondo")); // NOI18N
        panel_cantdeH.add(btn_additem);
        btn_additem.setBounds(40, 110, 50, 40);

        btn_minusitem.setFondo(bundle.getString("MisReservaciones.panelConFondo4.fondo")); // NOI18N
        panel_cantdeH.add(btn_minusitem);
        btn_minusitem.setBounds(110, 120, 50, 20);

        trans_CantidadH.setEnabled(false);
        panel_cantdeH.add(trans_CantidadH);
        trans_CantidadH.setBounds(70, 40, 50, 50);

        text_canthabitaciones.setText("Cantidad de habitaciones.");
        panel_cantdeH.add(text_canthabitaciones);
        text_canthabitaciones.setBounds(30, 20, 140, 14);

        panelBase1.add(panel_cantdeH);
        panel_cantdeH.setBounds(350, 140, 190, 160);

        panel_TiposdeH.setFondo(bundle.getString("MisReservaciones.panel_info.fondo")); // NOI18N

        text_tiposdeH.setText("Tipos de habitaciones.");
        panel_TiposdeH.add(text_tiposdeH);
        text_tiposdeH.setBounds(20, 30, 160, 40);

        cmbb_tiposdeH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbb_tiposdeHActionPerformed(evt);
            }
        });
        panel_TiposdeH.add(cmbb_tiposdeH);
        cmbb_tiposdeH.setBounds(20, 80, 150, 30);

        panelBase1.add(panel_TiposdeH);
        panel_TiposdeH.setBounds(40, 140, 200, 160);

        panel_save.setFondo(bundle.getString("MisReservaciones.panel_info.fondo")); // NOI18N
        panel_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_saveMouseClicked(evt);
            }
        });

        btn_save.setFondo(bundle.getString("MisReservaciones.panelConFondo4.fondo")); // NOI18N
        panel_save.add(btn_save);
        btn_save.setBounds(30, 20, 70, 60);

        text_save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text_save.setText("Guardar cambios.");
        panel_save.add(text_save);
        text_save.setBounds(10, 90, 100, 14);

        panelBase1.add(panel_save);
        panel_save.setBounds(80, 470, 120, 120);

        btn_regresar.setFondo(bundle.getString("MisReservaciones.btn_regresar.fondo")); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        panelBase1.add(btn_regresar);
        btn_regresar.setBounds(50, 40, 80, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbb_tiposdeHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbb_tiposdeHActionPerformed
        trans_CantidadH.setText(String.valueOf(Principal.getHabitaciones()[cmbb_tiposdeH.getSelectedIndex()].getN_habitaciones()));
    }//GEN-LAST:event_cmbb_tiposdeHActionPerformed

    private void panel_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_saveMouseClicked
        Principal.getHabitaciones()[cmbb_tiposdeH.getSelectedIndex()].setN_habitaciones(Integer.parseInt(trans_CantidadH.getText()));
    }//GEN-LAST:event_panel_saveMouseClicked

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        new MenuAdministrador().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarMouseClicked
            
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hotellounge.vista.base.PanelConFondo btn_additem;
    private hotellounge.vista.base.PanelConFondo btn_minusitem;
    private hotellounge.vista.base.PanelConFondo btn_regresar;
    private hotellounge.vista.base.PanelConFondo btn_save;
    private javax.swing.JComboBox cmbb_tiposdeH;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_TiposdeH;
    private hotellounge.vista.base.PanelConFondo panel_cantdeH;
    private hotellounge.vista.base.PanelConFondo panel_save;
    private javax.swing.JLabel text_canthabitaciones;
    private javax.swing.JLabel text_save;
    private javax.swing.JLabel text_tiposdeH;
    private hotellounge.vista.base.TransparentTextField trans_CantidadH;
    // End of variables declaration//GEN-END:variables
}
