/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * 15-dic-2015
 */
package hotellounge.vista;

import hotellounge.vista.base.VentanaBase_admin;

/**
 *
 * @author Oscar
 */
public class AdministrarHabitaciones extends VentanaBase_admin {

    /**
     * Creates new form AdministrarHabitaciones
     */
    public AdministrarHabitaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        cmbb_tiposdeH = new javax.swing.JComboBox();
        panel_TiposdeH = new hotellounge.vista.base.PanelConFondo();
        text_tiposdeH = new javax.swing.JLabel();
        panel_cantdeH = new hotellounge.vista.base.PanelConFondo();
        panel_cantdeH1 = new hotellounge.vista.base.PanelConFondo();
        text_cantdeH1 = new javax.swing.JLabel();
        btn_save1 = new hotellounge.vista.base.PanelConFondo();
        btn_save2 = new hotellounge.vista.base.PanelConFondo();
        panel_save = new hotellounge.vista.base.PanelConFondo();
        btn_save = new hotellounge.vista.base.PanelConFondo();
        text_save = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbb_tiposdeH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbb_tiposdeH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbb_tiposdeHActionPerformed(evt);
            }
        });
        panelBase1.add(cmbb_tiposdeH);
        cmbb_tiposdeH.setBounds(70, 230, 100, 20);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_TiposdeH.setFondo(bundle.getString("MisReservaciones.panel_info.fondo")); // NOI18N

        text_tiposdeH.setText("Tipos de habitaciones.");
        panel_TiposdeH.add(text_tiposdeH);
        text_tiposdeH.setBounds(20, 20, 180, 50);

        panelBase1.add(panel_TiposdeH);
        panel_TiposdeH.setBounds(40, 140, 200, 160);

        panel_cantdeH.setFondo(bundle.getString("MisReservaciones.panel_info.fondo")); // NOI18N

        panel_cantdeH1.setFondo(bundle.getString("MisReservaciones.panel_info.fondo")); // NOI18N

        text_cantdeH1.setText("Cantiidad de personas.");
        panel_cantdeH1.add(text_cantdeH1);
        text_cantdeH1.setBounds(20, 20, 180, 50);

        panel_cantdeH.add(panel_cantdeH1);
        panel_cantdeH1.setBounds(350, 140, 200, 160);

        btn_save1.setFondo(bundle.getString("MisReservaciones.panelConFondo4.fondo")); // NOI18N
        panel_cantdeH.add(btn_save1);
        btn_save1.setBounds(40, 110, 50, 40);

        btn_save2.setFondo(bundle.getString("MisReservaciones.panelConFondo4.fondo")); // NOI18N
        panel_cantdeH.add(btn_save2);
        btn_save2.setBounds(110, 120, 50, 20);

        panelBase1.add(panel_cantdeH);
        panel_cantdeH.setBounds(350, 140, 190, 160);

        panel_save.setFondo(bundle.getString("MisReservaciones.panel_info.fondo")); // NOI18N

        btn_save.setFondo(bundle.getString("MisReservaciones.panelConFondo4.fondo")); // NOI18N
        panel_save.add(btn_save);
        btn_save.setBounds(30, 20, 70, 60);

        text_save.setText("Guardar cambios.");
        panel_save.add(text_save);
        text_save.setBounds(20, 90, 100, 14);

        panelBase1.add(panel_save);
        panel_save.setBounds(80, 470, 120, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbb_tiposdeHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbb_tiposdeHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbb_tiposdeHActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hotellounge.vista.base.PanelConFondo btn_save;
    private hotellounge.vista.base.PanelConFondo btn_save1;
    private hotellounge.vista.base.PanelConFondo btn_save2;
    private javax.swing.JComboBox cmbb_tiposdeH;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_TiposdeH;
    private hotellounge.vista.base.PanelConFondo panel_cantdeH;
    private hotellounge.vista.base.PanelConFondo panel_cantdeH1;
    private hotellounge.vista.base.PanelConFondo panel_save;
    private javax.swing.JLabel text_cantdeH1;
    private javax.swing.JLabel text_save;
    private javax.swing.JLabel text_tiposdeH;
    // End of variables declaration//GEN-END:variables
}
