/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Dec 4, 2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.VentanaBase_usuario;

/**
 *
 * @author cocho
 */
public class Consultar extends VentanaBase_usuario {

    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panel_titulo = new hotellounge.vista.base.PanelConFondo();
        lbl_titulo = new javax.swing.JLabel();
        panel_izq = new hotellounge.vista.base.PanelConFondo();
        lbl_subtitulo1 = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        txt_cedula = new hotellounge.vista.base.TransparentTextField();
        btn_regresar = new hotellounge.vista.base.PanelConFondo();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_titulo.setFondo(bundle.getString("CrearReservaciones.panel_titulo.fondo")); // NOI18N

        lbl_titulo.setFont(Principal.getLetraTexto1());
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText(bundle.getString("CrearReservaciones.lbl_titulo.text")); // NOI18N
        panel_titulo.add(lbl_titulo);
        lbl_titulo.setBounds(20, 10, 380, 40);

        panelBase1.add(panel_titulo);
        panel_titulo.setBounds(200, 60, 420, 60);

        panel_izq.setFondo(bundle.getString("CrearReservaciones.panel_izq.fondo")); // NOI18N

        lbl_subtitulo1.setFont(Principal.getLetraTexto2());
        lbl_subtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo1.setText(bundle.getString("CrearReservaciones.lbl_subtitulo1.text")); // NOI18N
        panel_izq.add(lbl_subtitulo1);
        lbl_subtitulo1.setBounds(20, 20, 290, 30);

        lbl_cedula.setFont(Principal.getLetraTexto3());
        lbl_cedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cedula.setText(bundle.getString("CrearReservaciones.lbl_cedula.text")); // NOI18N
        panel_izq.add(lbl_cedula);
        lbl_cedula.setBounds(20, 70, 80, 30);

        txt_cedula.setText(bundle.getString("CrearReservaciones.txt_cedula.text")); // NOI18N
        txt_cedula.setToolTipText(bundle.getString("CrearReservaciones.txt_cedula.toolTipText")); // NOI18N
        panel_izq.add(txt_cedula);
        txt_cedula.setBounds(110, 70, 200, 30);

        panelBase1.add(panel_izq);
        panel_izq.setBounds(60, 160, 500, 350);

        btn_regresar.setFondo(bundle.getString("CrearReservaciones.btn_regresar.fondo")); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        panelBase1.add(btn_regresar);
        btn_regresar.setBounds(40, 70, 80, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        new MisReservaciones().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hotellounge.vista.base.PanelConFondo btn_regresar;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_subtitulo1;
    private javax.swing.JLabel lbl_titulo;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_izq;
    private hotellounge.vista.base.PanelConFondo panel_titulo;
    private hotellounge.vista.base.TransparentTextField txt_cedula;
    // End of variables declaration//GEN-END:variables
}
