/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Dec 4, 2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.VentanaBase_usuario;

/**
 *
 * @author cocho
 */
public class ConsultaDelAdministrador extends VentanaBase_usuario {

    /**
     * Creates new form ConsultaDelAdministrador
     */
    public ConsultaDelAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panel_titulo = new hotellounge.vista.base.PanelConFondo();
        lbl_titulo = new javax.swing.JLabel();
        panel_izq = new hotellounge.vista.base.PanelConFondo();
        btn_ingresar = new javax.swing.JButton();
        btn_ingresar1 = new javax.swing.JButton();
        btn_regresar = new hotellounge.vista.base.PanelConFondo();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_titulo.setFondo(bundle.getString("CrearReservaciones.panel_titulo.fondo")); // NOI18N

        lbl_titulo.setFont(Principal.getLetraTexto1());
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText(bundle.getString("CrearReservaciones.lbl_titulo.text")); // NOI18N
        panel_titulo.add(lbl_titulo);
        lbl_titulo.setBounds(20, 10, 380, 40);

        panelBase1.add(panel_titulo);
        panel_titulo.setBounds(200, 60, 420, 60);

        panel_izq.setFondo(bundle.getString("CrearReservaciones.panel_izq.fondo")); // NOI18N

        btn_ingresar.setText(bundle.getString("IniciarSesion.btn_ingresar.text")); // NOI18N
        btn_ingresar.setActionCommand("Mostrar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        panel_izq.add(btn_ingresar);
        btn_ingresar.setBounds(70, 60, 100, 40);

        btn_ingresar1.setText(bundle.getString("IniciarSesion.btn_ingresar.text")); // NOI18N
        btn_ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresar1ActionPerformed(evt);
            }
        });
        panel_izq.add(btn_ingresar1);
        btn_ingresar1.setBounds(70, 140, 100, 40);

        panelBase1.add(panel_izq);
        panel_izq.setBounds(100, 140, 630, 360);

        btn_regresar.setFondo(bundle.getString("CrearReservaciones.btn_regresar.fondo")); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        panelBase1.add(btn_regresar);
        btn_regresar.setBounds(40, 70, 80, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regresar2MouseClicked

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        new MisReservaciones().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarMouseClicked

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        if(this.txt_usuario.getText().equals("admin") && new String(this.txt_password.getPassword()).equals("123")){
            new MenuAdministrador().setVisible(true);
            this.dispose();
            this.getParent().setVisible(false);
        } else
        mostrar_error("Usuario o contraseña erróneos");
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresar1ActionPerformed
        if(this.txt_usuario.getText().equals("admin") && new String(this.txt_password.getPassword()).equals("123")){
            new MenuAdministrador().setVisible(true);
            this.dispose();
            this.getParent().setVisible(false);
        } else
        mostrar_error("Usuario o contraseña erróneos");
    }//GEN-LAST:event_btn_ingresar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_ingresar1;
    private hotellounge.vista.base.PanelConFondo btn_regresar;
    private javax.swing.JLabel lbl_titulo;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_izq;
    private hotellounge.vista.base.PanelConFondo panel_titulo;
    // End of variables declaration//GEN-END:variables
}
