/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Nov 30, 2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.TransparentTextField;
import hotellounge.vista.base.VentanaBase_usuario;
import java.util.logging.Logger;

/**
 *
 * @author jmora
 */
public class CrearReservaciones extends VentanaBase_usuario {

    private static final Logger LOG = Logger.getLogger(CrearReservaciones.class.getName());
 
    /**
     * Creates new form CrearReservaciones
     */
    public CrearReservaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panel_titulo = new hotellounge.vista.base.PanelConFondo();
        lbl_titulo = new javax.swing.JLabel();
        panel_izq = new hotellounge.vista.base.PanelConFondo();
        lbl_subtitulo1 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        lbl_nombre2 = new javax.swing.JLabel();
        txt_correo = new TransparentTextField();
        txt_nombre = new TransparentTextField();
        txt_telefono = new TransparentTextField();
        lbl_nombre3 = new javax.swing.JLabel();
        txt_cedula = new hotellounge.vista.base.TransparentTextField();
        panel_izq1 = new hotellounge.vista.base.PanelConFondo();
        lbl_subtitulo2 = new javax.swing.JLabel();
        lbl_nombre4 = new javax.swing.JLabel();
        cmb_tipoHabitacion = new hotellounge.vista.base.TransparentComboBox();
        lbl_fechaReservacion = new javax.swing.JLabel();
        cmb_cantidadHabitaciones = new hotellounge.vista.base.TransparentComboBox();
        lbl_nombre6 = new javax.swing.JLabel();
        fecha_reservacion = new datechooser.beans.DateChooserCombo();
        btn_regresar = new hotellounge.vista.base.PanelConFondo();
        jPanel1 = new javax.swing.JPanel();
        lbl_nombre7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_titulo.setFondo(bundle.getString("CrearReservaciones.panel_titulo.fondo")); // NOI18N

        lbl_titulo.setFont(Principal.getLetraTexto1());
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText(bundle.getString("CrearReservaciones.lbl_titulo.text")); // NOI18N
        panel_titulo.add(lbl_titulo);
        lbl_titulo.setBounds(20, 10, 380, 40);

        panelBase1.add(panel_titulo);
        panel_titulo.setBounds(200, 60, 420, 60);

        panel_izq.setFondo(bundle.getString("CrearReservaciones.panel_izq.fondo")); // NOI18N

        lbl_subtitulo1.setFont(Principal.getLetraTexto2());
        lbl_subtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo1.setText(bundle.getString("CrearReservaciones.lbl_subtitulo1.text")); // NOI18N
        panel_izq.add(lbl_subtitulo1);
        lbl_subtitulo1.setBounds(20, 20, 290, 30);

        lbl_nombre.setFont(Principal.getLetraTexto3());
        lbl_nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre.setText(bundle.getString("CrearReservaciones.lbl_nombre.text")); // NOI18N
        panel_izq.add(lbl_nombre);
        lbl_nombre.setBounds(20, 190, 80, 30);

        lbl_cedula.setFont(Principal.getLetraTexto3());
        lbl_cedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cedula.setText(bundle.getString("CrearReservaciones.lbl_cedula.text")); // NOI18N
        panel_izq.add(lbl_cedula);
        lbl_cedula.setBounds(20, 70, 80, 30);

        lbl_nombre2.setFont(Principal.getLetraTexto3());
        lbl_nombre2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre2.setText(bundle.getString("CrearReservaciones.lbl_nombre2.text")); // NOI18N
        panel_izq.add(lbl_nombre2);
        lbl_nombre2.setBounds(20, 150, 80, 30);

        txt_correo.setText(bundle.getString("CrearReservaciones.txt_correo.text")); // NOI18N
        txt_correo.setToolTipText(bundle.getString("CrearReservaciones.txt_correo.toolTipText")); // NOI18N
        panel_izq.add(txt_correo);
        txt_correo.setBounds(110, 190, 200, 30);

        txt_nombre.setText(bundle.getString("CrearReservaciones.txt_nombre.text")); // NOI18N
        txt_nombre.setToolTipText(bundle.getString("CrearReservaciones.txt_nombre.toolTipText")); // NOI18N
        panel_izq.add(txt_nombre);
        txt_nombre.setBounds(110, 110, 200, 30);

        txt_telefono.setText(bundle.getString("CrearReservaciones.txt_telefono.text")); // NOI18N
        txt_telefono.setToolTipText(bundle.getString("CrearReservaciones.txt_telefono.toolTipText")); // NOI18N
        panel_izq.add(txt_telefono);
        txt_telefono.setBounds(110, 150, 200, 30);

        lbl_nombre3.setFont(Principal.getLetraTexto3());
        lbl_nombre3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre3.setText(bundle.getString("CrearReservaciones.lbl_nombre3.text")); // NOI18N
        panel_izq.add(lbl_nombre3);
        lbl_nombre3.setBounds(20, 110, 80, 30);

        txt_cedula.setText(bundle.getString("CrearReservaciones.txt_cedula.text")); // NOI18N
        txt_cedula.setToolTipText(bundle.getString("CrearReservaciones.txt_cedula.toolTipText")); // NOI18N
        panel_izq.add(txt_cedula);
        txt_cedula.setBounds(110, 70, 200, 30);

        panelBase1.add(panel_izq);
        panel_izq.setBounds(60, 160, 330, 350);

        panel_izq1.setFondo(bundle.getString("CrearReservaciones.panel_izq1.fondo")); // NOI18N

        lbl_subtitulo2.setFont(Principal.getLetraTexto2());
        lbl_subtitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo2.setText(bundle.getString("CrearReservaciones.lbl_subtitulo2.text")); // NOI18N
        panel_izq1.add(lbl_subtitulo2);
        lbl_subtitulo2.setBounds(20, 20, 290, 30);

        lbl_nombre4.setFont(Principal.getLetraTexto3());
        lbl_nombre4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre4.setText(bundle.getString("CrearReservaciones.lbl_nombre4.text")); // NOI18N
        panel_izq1.add(lbl_nombre4);
        lbl_nombre4.setBounds(20, 60, 180, 30);
        panel_izq1.add(cmb_tipoHabitacion);
        cmb_tipoHabitacion.setBounds(40, 90, 250, 30);

        lbl_fechaReservacion.setFont(Principal.getLetraTexto3());
        lbl_fechaReservacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_fechaReservacion.setText(bundle.getString("CrearReservaciones.lbl_fechaReservacion.text")); // NOI18N
        panel_izq1.add(lbl_fechaReservacion);
        lbl_fechaReservacion.setBounds(20, 190, 160, 30);
        panel_izq1.add(cmb_cantidadHabitaciones);
        cmb_cantidadHabitaciones.setBounds(40, 150, 250, 30);

        lbl_nombre6.setFont(Principal.getLetraTexto3());
        lbl_nombre6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre6.setText(bundle.getString("CrearReservaciones.lbl_nombre6.text")); // NOI18N
        panel_izq1.add(lbl_nombre6);
        lbl_nombre6.setBounds(20, 120, 180, 30);
        panel_izq1.add(fecha_reservacion);
        fecha_reservacion.setBounds(190, 190, 100, 30);

        panelBase1.add(panel_izq1);
        panel_izq1.setBounds(430, 160, 330, 350);

        btn_regresar.setFondo(bundle.getString("CrearReservaciones.btn_regresar.fondo")); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        panelBase1.add(btn_regresar);
        btn_regresar.setBounds(40, 70, 80, 40);

        lbl_nombre7.setFont(Principal.getLetraTexto3());
        lbl_nombre7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre7.setText(bundle.getString("CrearReservaciones.lbl_nombre7.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_nombre7)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelBase1.add(jPanel1);
        jPanel1.setBounds(100, 520, 100, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        new MisReservaciones().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hotellounge.vista.base.PanelConFondo btn_regresar;
    private hotellounge.vista.base.TransparentComboBox cmb_cantidadHabitaciones;
    private hotellounge.vista.base.TransparentComboBox cmb_tipoHabitacion;
    private datechooser.beans.DateChooserCombo fecha_reservacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_fechaReservacion;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombre2;
    private javax.swing.JLabel lbl_nombre3;
    private javax.swing.JLabel lbl_nombre4;
    private javax.swing.JLabel lbl_nombre6;
    private javax.swing.JLabel lbl_nombre7;
    private javax.swing.JLabel lbl_subtitulo1;
    private javax.swing.JLabel lbl_subtitulo2;
    private javax.swing.JLabel lbl_titulo;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_izq;
    private hotellounge.vista.base.PanelConFondo panel_izq1;
    private hotellounge.vista.base.PanelConFondo panel_titulo;
    private hotellounge.vista.base.TransparentTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
