/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Nov 30, 2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.TransparentTextField;
import hotellounge.vista.base.VentanaBase_usuario;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jmora
 */
public class CrearReservaciones extends VentanaBase_usuario {

    private static final Logger LOG = Logger.getLogger(CrearReservaciones.class.getName());

    /**
     * Creates new form CrearReservaciones
     */
    public CrearReservaciones() {
        initComponents();
    }

    public void validarCorreo() {
        String correo;
        int a;
        int b;

        correo = txt_correo.getText();

        a = correo.indexOf("@");
        b = correo.indexOf(".com");

        try {
            if (correo.contains("@")) {
                if (correo.contains(".com")) {
                    if (a > b) {

                        mostrar_error("Su correo esta mal escrito");
                    }
                } else {
                    mostrar_error("Solo correos con terminacion en '.com' son válidos");
                }
            } else {
                mostrar_error("Digite un correo válido");
            }
        } catch (Exception e) {
            mostrar_error("Digite un correo válido");
        }
    }

    public void mostrar(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(null, mensaje);
    }

    public static void mostrar_error(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, "¡Error!", javax.swing.JOptionPane.ERROR_MESSAGE);
    }

    public void soloLetras(JTextField txt) {
        txt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    e.consume();
                }
            }
        });
    }

    public void soloNumeros(JTextField txt) {
        txt.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panel_titulo = new hotellounge.vista.base.PanelConFondo();
        lbl_CrearReservaciones = new javax.swing.JLabel();
        panel_izq = new hotellounge.vista.base.PanelConFondo();
        lbl_subtitulo1 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        lbl_nombre2 = new javax.swing.JLabel();
        txt_correo = new TransparentTextField();
        txt_nombre = new TransparentTextField();
        txt_telefono = new TransparentTextField();
        lbl_nombre3 = new javax.swing.JLabel();
        txt_cedula = new hotellounge.vista.base.TransparentTextField();
        panel_izq1 = new hotellounge.vista.base.PanelConFondo();
        lbl_subtitulo2 = new javax.swing.JLabel();
        lbl_nombre4 = new javax.swing.JLabel();
        cmb_tipoHabitacion = new hotellounge.vista.base.TransparentComboBox();
        lbl_fechaReservacion = new javax.swing.JLabel();
        fecha_reservacion = new datechooser.beans.DateChooserCombo();
        lbl_cantidadPersonas = new javax.swing.JLabel();
        txt_cantidadDias = new hotellounge.vista.base.TransparentTextField();
        txt_cantidadPersonas = new hotellounge.vista.base.TransparentTextField();
        lbl_cantidadDias = new javax.swing.JLabel();
        Boton_reservar = new javax.swing.JButton();
        btn_regresar = new hotellounge.vista.base.PanelConFondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_titulo.setFondo(bundle.getString("CrearReservaciones.panel_titulo.fondo")); // NOI18N

        lbl_CrearReservaciones.setFont(Principal.getLetraTexto1());
        lbl_CrearReservaciones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_CrearReservaciones.setText(bundle.getString("CrearReservaciones.lbl_CrearReservaciones.text")); // NOI18N
        panel_titulo.add(lbl_CrearReservaciones);
        lbl_CrearReservaciones.setBounds(20, 10, 380, 40);

        panelBase1.add(panel_titulo);
        panel_titulo.setBounds(200, 60, 420, 60);

        panel_izq.setFondo(bundle.getString("CrearReservaciones.panel_izq.fondo")); // NOI18N

        lbl_subtitulo1.setFont(Principal.getLetraTexto2());
        lbl_subtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo1.setText(bundle.getString("CrearReservaciones.lbl_subtitulo1.text")); // NOI18N
        panel_izq.add(lbl_subtitulo1);
        lbl_subtitulo1.setBounds(20, 20, 290, 30);

        lbl_nombre.setFont(Principal.getLetraTexto3());
        lbl_nombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre.setText(bundle.getString("CrearReservaciones.lbl_nombre.text")); // NOI18N
        panel_izq.add(lbl_nombre);
        lbl_nombre.setBounds(20, 190, 80, 30);

        lbl_cedula.setFont(Principal.getLetraTexto3());
        lbl_cedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cedula.setText(bundle.getString("CrearReservaciones.lbl_cedula.text")); // NOI18N
        panel_izq.add(lbl_cedula);
        lbl_cedula.setBounds(20, 70, 80, 30);

        lbl_nombre2.setFont(Principal.getLetraTexto3());
        lbl_nombre2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre2.setText(bundle.getString("CrearReservaciones.lbl_nombre2.text")); // NOI18N
        panel_izq.add(lbl_nombre2);
        lbl_nombre2.setBounds(20, 150, 80, 30);

        txt_correo.setText(bundle.getString("CrearReservaciones.txt_correo.text")); // NOI18N
        txt_correo.setToolTipText(bundle.getString("CrearReservaciones.txt_correo.toolTipText")); // NOI18N
        txt_correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_correoFocusLost(evt);
            }
        });
        panel_izq.add(txt_correo);
        txt_correo.setBounds(110, 190, 200, 30);

        txt_nombre.setText(bundle.getString("CrearReservaciones.txt_nombre.text")); // NOI18N
        txt_nombre.setToolTipText(bundle.getString("CrearReservaciones.txt_nombre.toolTipText")); // NOI18N
        soloLetras(txt_nombre);
        panel_izq.add(txt_nombre);
        txt_nombre.setBounds(110, 110, 200, 30);

        txt_telefono.setText(bundle.getString("CrearReservaciones.txt_telefono.text")); // NOI18N
        txt_telefono.setToolTipText(bundle.getString("CrearReservaciones.txt_telefono.toolTipText")); // NOI18N
        soloNumeros(txt_telefono);
        panel_izq.add(txt_telefono);
        txt_telefono.setBounds(110, 150, 200, 30);

        lbl_nombre3.setFont(Principal.getLetraTexto3());
        lbl_nombre3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre3.setText(bundle.getString("CrearReservaciones.lbl_nombre3.text")); // NOI18N
        panel_izq.add(lbl_nombre3);
        lbl_nombre3.setBounds(20, 110, 80, 30);

        txt_cedula.setText(bundle.getString("CrearReservaciones.txt_cedula.text")); // NOI18N
        txt_cedula.setToolTipText(bundle.getString("CrearReservaciones.txt_cedula.toolTipText")); // NOI18N
        soloNumeros(txt_cedula);
        panel_izq.add(txt_cedula);
        txt_cedula.setBounds(110, 70, 200, 30);

        panelBase1.add(panel_izq);
        panel_izq.setBounds(60, 160, 330, 350);

        panel_izq1.setFondo(bundle.getString("CrearReservaciones.panel_izq1.fondo")); // NOI18N

        lbl_subtitulo2.setFont(Principal.getLetraTexto2());
        lbl_subtitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo2.setText(bundle.getString("CrearReservaciones.lbl_subtitulo2.text")); // NOI18N
        panel_izq1.add(lbl_subtitulo2);
        lbl_subtitulo2.setBounds(20, 20, 290, 30);

        lbl_nombre4.setFont(Principal.getLetraTexto3());
        lbl_nombre4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_nombre4.setText(bundle.getString("CrearReservaciones.lbl_nombre4.text")); // NOI18N
        panel_izq1.add(lbl_nombre4);
        lbl_nombre4.setBounds(10, 60, 180, 30);

        cmb_tipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoHabitacionActionPerformed(evt);
            }
        });
        panel_izq1.add(cmb_tipoHabitacion);
        cmb_tipoHabitacion.setBounds(40, 90, 250, 30);

        lbl_fechaReservacion.setFont(Principal.getLetraTexto3());
        lbl_fechaReservacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_fechaReservacion.setText(bundle.getString("CrearReservaciones.lbl_fechaReservacion.text")); // NOI18N
        panel_izq1.add(lbl_fechaReservacion);
        lbl_fechaReservacion.setBounds(20, 220, 160, 30);
        panel_izq1.add(fecha_reservacion);
        fecha_reservacion.setBounds(190, 220, 100, 30);

        lbl_cantidadPersonas.setFont(Principal.getLetraTexto3());
        lbl_cantidadPersonas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cantidadPersonas.setText(bundle.getString("CrearReservaciones.lbl_cantidadPersonas.text")); // NOI18N
        panel_izq1.add(lbl_cantidadPersonas);
        lbl_cantidadPersonas.setBounds(10, 170, 180, 30);

        txt_cantidadDias.setText(bundle.getString("CrearReservaciones.txt_cantidadDias.text")); // NOI18N
        txt_cantidadDias.setToolTipText(bundle.getString("CrearReservaciones.txt_cantidadDias.toolTipText")); // NOI18N
        txt_cantidadDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadDiasActionPerformed(evt);
            }
        });
        soloNumeros(txt_cantidadDias);
        panel_izq1.add(txt_cantidadDias);
        txt_cantidadDias.setBounds(210, 130, 80, 30);

        txt_cantidadPersonas.setText(bundle.getString("CrearReservaciones.txt_cantidadPersonas.text")); // NOI18N
        txt_cantidadPersonas.setToolTipText(bundle.getString("CrearReservaciones.txt_cantidadPersonas.toolTipText")); // NOI18N
        soloNumeros(txt_cantidadPersonas);
        panel_izq1.add(txt_cantidadPersonas);
        txt_cantidadPersonas.setBounds(210, 170, 80, 30);

        lbl_cantidadDias.setFont(Principal.getLetraTexto3());
        lbl_cantidadDias.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_cantidadDias.setText(bundle.getString("CrearReservaciones.lbl_cantidadDias.text")); // NOI18N
        panel_izq1.add(lbl_cantidadDias);
        lbl_cantidadDias.setBounds(30, 130, 160, 30);

        Boton_reservar.setText(bundle.getString("CrearReservaciones.Boton_reservar.text")); // NOI18N
        Boton_reservar.setActionCommand(bundle.getString("CrearReservaciones.Boton_reservar.actionCommand")); // NOI18N
        panel_izq1.add(Boton_reservar);
        Boton_reservar.setBounds(140, 280, 77, 23);
        Boton_reservar.getAccessibleContext().setAccessibleName(bundle.getString("CrearReservaciones.Boton_reservar.AccessibleContext.accessibleName")); // NOI18N

        panelBase1.add(panel_izq1);
        panel_izq1.setBounds(430, 160, 330, 350);

        btn_regresar.setFondo(bundle.getString("CrearReservaciones.btn_regresar.fondo")); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        panelBase1.add(btn_regresar);
        btn_regresar.setBounds(40, 70, 80, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBase1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        new MisReservaciones().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarMouseClicked

    private void cmb_tipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoHabitacionActionPerformed

    private void txt_cantidadDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadDiasActionPerformed

    private void txt_correoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_correoFocusLost
        validarCorreo();
    }//GEN-LAST:event_txt_correoFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_reservar;
    private hotellounge.vista.base.PanelConFondo btn_regresar;
    private hotellounge.vista.base.TransparentComboBox cmb_tipoHabitacion;
    private datechooser.beans.DateChooserCombo fecha_reservacion;
    private javax.swing.JLabel lbl_CrearReservaciones;
    private javax.swing.JLabel lbl_cantidadDias;
    private javax.swing.JLabel lbl_cantidadPersonas;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_fechaReservacion;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_nombre2;
    private javax.swing.JLabel lbl_nombre3;
    private javax.swing.JLabel lbl_nombre4;
    private javax.swing.JLabel lbl_subtitulo1;
    private javax.swing.JLabel lbl_subtitulo2;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_izq;
    private hotellounge.vista.base.PanelConFondo panel_izq1;
    private hotellounge.vista.base.PanelConFondo panel_titulo;
    private hotellounge.vista.base.TransparentTextField txt_cantidadDias;
    private hotellounge.vista.base.TransparentTextField txt_cantidadPersonas;
    private hotellounge.vista.base.TransparentTextField txt_cedula;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
