/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * 05-dic-2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.TransparentTextField;
import hotellounge.vista.base.VentanaBase_usuario;
import java.util.logging.Logger;

/**
 *
 * @author Oscar
 */
public class EditarReservacion extends javax.swing.JFrame {

    /**
     * Creates new form EditarReservacion
     */
    public EditarReservacion() {
        initComponents();
    }

    private static final Logger LOG = Logger.getLogger(EditarReservacion.class.getName());
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {                                          
        new Home().setVisible(true);
        this.dispose();
    
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
   
}