/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Nov 30, 2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.VentanaBase_usuario;

/**
 *
 * @author jmora
 */
public class Home extends VentanaBase_usuario {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new hotellounge.vista.base.PanelBase();
        panelConFondo2 = new hotellounge.vista.base.PanelConFondo();
        panel_titulos = new hotellounge.vista.base.PanelConFondo();
        lbl_subtitulo1 = new javax.swing.JLabel();
        lbl_titulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panelConFondo2.setFondo(bundle.getString("Home.panelConFondo2.fondo")); // NOI18N
        panelConFondo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelConFondo2MouseClicked(evt);
            }
        });
        panelBase.add(panelConFondo2);
        panelConFondo2.setBounds(260, 230, 330, 110);

        panel_titulos.setFondo(bundle.getString("Home.panel_titulos.fondo")); // NOI18N

        lbl_subtitulo1.setFont(Principal.getLetraTexto1());
        lbl_subtitulo1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_subtitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo1.setText(bundle.getString("Home.lbl_subtitulo1.text")); // NOI18N
        panel_titulos.add(lbl_subtitulo1);
        lbl_subtitulo1.setBounds(20, 10, 500, 50);

        lbl_titulo1.setFont(Principal.getLetraTitulo1());
        lbl_titulo1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo1.setText(bundle.getString("Home.lbl_titulo1.text")); // NOI18N
        panel_titulos.add(lbl_titulo1);
        lbl_titulo1.setBounds(20, 50, 500, 40);

        panelBase.add(panel_titulos);
        panel_titulos.setBounds(140, 60, 540, 110);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelConFondo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelConFondo2MouseClicked
        new MisReservaciones().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_panelConFondo2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_subtitulo1;
    private javax.swing.JLabel lbl_titulo1;
    private hotellounge.vista.base.PanelBase panelBase;
    private hotellounge.vista.base.PanelConFondo panelConFondo2;
    private hotellounge.vista.base.PanelConFondo panel_titulos;
    // End of variables declaration//GEN-END:variables
}
