/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Dec 2, 2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.VentanaBase_admin;

/**
 *
 * @author jmora
 */
public class MenuAdministrador extends VentanaBase_admin {

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panel_titulo = new hotellounge.vista.base.PanelConFondo();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_titulo.setFondo(bundle.getString("MenuAdministrador.panel_titulo.fondo")); // NOI18N

        jLabel1.setFont(Principal.getLetraTexto1());
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("MenuAdministrador.jLabel1.text")); // NOI18N
        panel_titulo.add(jLabel1);
        jLabel1.setBounds(20, 10, 390, 60);

        panelBase1.add(panel_titulo);
        panel_titulo.setBounds(200, 60, 430, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_titulo;
    // End of variables declaration//GEN-END:variables
}
