/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Dec 2, 2015
 */
package hotellounge.vista;

import hotellounge.Principal;
import hotellounge.vista.base.VentanaBase_admin;

/**
 *
 * @author jmora
 */
public class MenuAdministrador extends VentanaBase_admin {

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panel_titulo = new hotellounge.vista.base.PanelConFondo();
        jLabel1 = new javax.swing.JLabel();
        panel_info = new hotellounge.vista.base.PanelConFondo();
        AdministrarReserv = new hotellounge.vista.base.PanelConFondo();
        text_adminreserv = new javax.swing.JLabel();
        AdminReserv = new hotellounge.vista.base.PanelConFondo();
        jLabel3 = new javax.swing.JLabel();
        AdministrarHabitaciones = new hotellounge.vista.base.PanelConFondo();
        text_adminhabitaciones = new javax.swing.JLabel();
        AdminHabitaciones = new hotellounge.vista.base.PanelConFondo();
        jLabel4 = new javax.swing.JLabel();
        DeleteReservP = new hotellounge.vista.base.PanelConFondo();
        text_deletereserv = new javax.swing.JLabel();
        iconDeleteReserv = new hotellounge.vista.base.PanelConFondo();
        jLabel5 = new javax.swing.JLabel();
        btn_regresar = new hotellounge.vista.base.PanelConFondo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/Bundle"); // NOI18N
        panel_titulo.setFondo(bundle.getString("MenuAdministrador.panel_titulo.fondo")); // NOI18N

        jLabel1.setFont(Principal.getLetraTexto1());
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("MenuAdministrador.jLabel1.text")); // NOI18N
        panel_titulo.add(jLabel1);
        jLabel1.setBounds(20, 10, 390, 60);

        panelBase1.add(panel_titulo);
        panel_titulo.setBounds(200, 60, 430, 80);

        panel_info.setFondo(bundle.getString("MenuAdministrador.panel_info.fondo")); // NOI18N

        AdministrarReserv.setFondo(bundle.getString("MenuAdministrador.AdministrarReserv.fondo")); // NOI18N

        text_adminreserv.setText(bundle.getString("MenuAdministrador.text_adminreserv.text")); // NOI18N
        AdministrarReserv.add(text_adminreserv);
        text_adminreserv.setBounds(20, 90, 150, 30);

        AdminReserv.setFondo(bundle.getString("MenuAdministrador.AdminReserv.fondo")); // NOI18N

        jLabel3.setText(bundle.getString("MenuAdministrador.jLabel3.text")); // NOI18N
        AdminReserv.add(jLabel3);
        jLabel3.setBounds(10, 80, 130, 30);

        AdministrarReserv.add(AdminReserv);
        AdminReserv.setBounds(30, 10, 120, 80);

        panel_info.add(AdministrarReserv);
        AdministrarReserv.setBounds(60, 40, 180, 120);
        AdministrarReserv.getAccessibleContext().setAccessibleParent(panelBase1);

        AdministrarHabitaciones.setFondo(bundle.getString("MenuAdministrador.AdministrarHabitaciones.fondo")); // NOI18N
        AdministrarHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdministrarHabitacionesMouseClicked(evt);
            }
        });

        text_adminhabitaciones.setText(bundle.getString("MenuAdministrador.text_adminhabitaciones.text")); // NOI18N
        AdministrarHabitaciones.add(text_adminhabitaciones);
        text_adminhabitaciones.setBounds(20, 90, 150, 30);

        AdminHabitaciones.setFondo(bundle.getString("MenuAdministrador.AdminHabitaciones.fondo")); // NOI18N

        jLabel4.setText(bundle.getString("MenuAdministrador.jLabel4.text")); // NOI18N
        AdminHabitaciones.add(jLabel4);
        jLabel4.setBounds(10, 80, 130, 30);

        AdministrarHabitaciones.add(AdminHabitaciones);
        AdminHabitaciones.setBounds(40, 10, 120, 80);

        panel_info.add(AdministrarHabitaciones);
        AdministrarHabitaciones.setBounds(380, 40, 180, 120);

        DeleteReservP.setFondo(bundle.getString("MenuAdministrador.DeleteReservP.fondo")); // NOI18N

        text_deletereserv.setText(bundle.getString("MenuAdministrador.text_deletereserv.text")); // NOI18N
        DeleteReservP.add(text_deletereserv);
        text_deletereserv.setBounds(20, 90, 150, 30);

        iconDeleteReserv.setFondo(bundle.getString("MenuAdministrador.iconDeleteReserv.fondo")); // NOI18N

        jLabel5.setText(bundle.getString("MenuAdministrador.jLabel5.text")); // NOI18N
        iconDeleteReserv.add(jLabel5);
        jLabel5.setBounds(10, 80, 130, 30);

        DeleteReservP.add(iconDeleteReserv);
        iconDeleteReserv.setBounds(30, 10, 110, 80);

        panel_info.add(DeleteReservP);
        DeleteReservP.setBounds(70, 190, 180, 120);

        panelBase1.add(panel_info);
        panel_info.setBounds(70, 160, 640, 350);

        btn_regresar.setFondo(bundle.getString("MenuAdministrador.btn_regresar.fondo")); // NOI18N
        btn_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_regresarMouseClicked(evt);
            }
        });
        panelBase1.add(btn_regresar);
        btn_regresar.setBounds(40, 70, 80, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_regresarMouseClicked
        new Home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarMouseClicked

    private void AdministrarHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdministrarHabitacionesMouseClicked
        // TODO add your handling code here:
        new ManejarHabitaciones().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_AdministrarHabitacionesMouseClicked

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hotellounge.vista.base.PanelConFondo AdminHabitaciones;
    private hotellounge.vista.base.PanelConFondo AdminReserv;
    private hotellounge.vista.base.PanelConFondo AdministrarHabitaciones;
    private hotellounge.vista.base.PanelConFondo AdministrarReserv;
    private hotellounge.vista.base.PanelConFondo DeleteReservP;
    private hotellounge.vista.base.PanelConFondo btn_regresar;
    private hotellounge.vista.base.PanelConFondo iconDeleteReserv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panel_info;
    private hotellounge.vista.base.PanelConFondo panel_titulo;
    private javax.swing.JLabel text_adminhabitaciones;
    private javax.swing.JLabel text_adminreserv;
    private javax.swing.JLabel text_deletereserv;
    // End of variables declaration//GEN-END:variables
}
