/*
 * HotelLounge
 * José David Mora Loría
 * Oscar Mauricio Gil
 * Melvin Arce Rodriguez
 * Nov 25, 2015
 */
package hotellounge.vista.base;

import hotellounge.Principal;
import hotellounge.vista.MenuAdministrador;
import javax.swing.JFrame;

/**
 *
 * @author jmora
 */
public class IniciarSesion extends javax.swing.JDialog {

    /**
     * Creates new form IniciarSesion
     */
    public IniciarSesion(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase1 = new hotellounge.vista.base.PanelBase();
        panelTitulo = new hotellounge.vista.base.PanelConFondo();
        jLabel1 = new javax.swing.JLabel();
        panelInformacion = new hotellounge.vista.base.PanelConFondo();
        lbl_password = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new TransparentTextField();
        txt_password = new TransparentPasswordField();
        btn_ingresar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("hotellounge/vista/base/Bundle"); // NOI18N
        panelTitulo.setFondo(bundle.getString("IniciarSesion.panelTitulo.fondo")); // NOI18N

        jLabel1.setFont(Principal.getLetraTexto1());
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(bundle.getString("IniciarSesion.jLabel1.text")); // NOI18N
        panelTitulo.add(jLabel1);
        jLabel1.setBounds(20, 10, 330, 40);

        panelBase1.add(panelTitulo);
        panelTitulo.setBounds(50, 20, 370, 60);

        panelInformacion.setFondo(bundle.getString("IniciarSesion.panelInformacion.fondo")); // NOI18N

        lbl_password.setFont(Principal.getLetraTexto3());
        lbl_password.setForeground(new java.awt.Color(0, 0, 0));
        lbl_password.setText(bundle.getString("IniciarSesion.lbl_password.text")); // NOI18N
        panelInformacion.add(lbl_password);
        lbl_password.setBounds(30, 80, 100, 40);

        lbl_usuario.setFont(Principal.getLetraTexto3());
        lbl_usuario.setForeground(new java.awt.Color(0, 0, 0));
        lbl_usuario.setText(bundle.getString("IniciarSesion.lbl_usuario.text")); // NOI18N
        panelInformacion.add(lbl_usuario);
        lbl_usuario.setBounds(30, 30, 100, 40);

        txt_usuario.setText(bundle.getString("IniciarSesion.txt_usuario.text")); // NOI18N
        txt_usuario.setToolTipText(bundle.getString("IniciarSesion.txt_usuario.toolTipText")); // NOI18N
        panelInformacion.add(txt_usuario);
        txt_usuario.setBounds(140, 30, 200, 40);

        txt_password.setText(bundle.getString("IniciarSesion.txt_password.text")); // NOI18N
        txt_password.setToolTipText(bundle.getString("IniciarSesion.txt_password.toolTipText")); // NOI18N
        panelInformacion.add(txt_password);
        txt_password.setBounds(140, 80, 200, 40);

        btn_ingresar.setText(bundle.getString("IniciarSesion.btn_ingresar.text")); // NOI18N
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        panelInformacion.add(btn_ingresar);
        btn_ingresar.setBounds(240, 160, 100, 40);

        btn_cancelar.setText(bundle.getString("IniciarSesion.btn_cancelar.text")); // NOI18N
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        panelInformacion.add(btn_cancelar);
        btn_cancelar.setBounds(30, 160, 100, 40);

        panelBase1.add(panelInformacion);
        panelInformacion.setBounds(50, 90, 370, 230);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBase1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        if(this.txt_usuario.getText().equals("admin") && new String(this.txt_password.getPassword()).equals("123")){
            new MenuAdministrador().setVisible(true);
            this.dispose();
            this.getParent().setVisible(false);
        } else 
            mostrar_error("Usuario o contraseña erróneos");
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void mostrar_error(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "¡Error!", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_usuario;
    private hotellounge.vista.base.PanelBase panelBase1;
    private hotellounge.vista.base.PanelConFondo panelInformacion;
    private hotellounge.vista.base.PanelConFondo panelTitulo;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
